CREATE TABLE cakes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    calories    DECIMAL,
    image       VARCHAR(255),
    price       DECIMAL,
    weight      DECIMAL,
    composition VARCHAR(255),
    shelf_life  VARCHAR(255),
    CONSTRAINT pk_cakes PRIMARY KEY (id)
);